services:
  - type: web
    name: gestion-compte-api
    env: docker
    dockerImage: docker.io/<dockerhub_user>/gestion_compte:latest
    region: frankfurt
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      # ... autres vars (DB_*, PG*) ...